# Generated by Django 6.0.7 on 2026-07-30 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fecha_vencimiento',
            new_name='fecha_vencimiento_sla',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_REVISION', 'En revision'), ('ESPERANDO_CLIENTE', 'Esperando cliente'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='NUEVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
